version: '3.3'

services:
  minio:
    image: "emqx/emqx:4.2.3"
    environment:
      - TZ=Asia/Shanghai
    ports: 
      - "1883:1883" 
      - "8083:8083"
      - "8883:8883"
      - "8084:8084"
      - "18083:18083"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    container_name: emqx
