version: '3.3'

services:
  mysql:
    image: mysql:5.7
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=ROot@2018
    restart: always
    network_mode: "host"
    command: /entrypoint.sh mysqld
    volumes:
      - ./data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    container_name: mysql
