version: '3'
services:
  db:
    image: 'mysql:5.7'
    restart: always
    container_name: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: MyCloud@2019
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql/config/my.cnf:/etc/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d/
    ports:
      - '3308:3306'
volumes:
  data:
    driver: local
