version: '3.6'

services:
  consul1:
    image: consul:latest
    container_name: consul1
    restart: always
    command: agent -server -bootstrap -ui -client='0.0.0.0'
    ports:
      - "8500:8500"
    volumes:
      - ./data/consul:/consul/data
      - /etc/localtime:/etc/localtime:ro
