version: "3"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    environment:
    - MODE=standalone
    volumes:
    - ./logs:/home/nacos/logs
    -  ./config/custom.properties:/home/nacos/init.d/custom.properties
    ports:
    - "8848:8848"
    restart: always
