version: '3'

services:

  kong-database:
    image: postgres:9.6
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kong-net
    restart: always

  kong-migration:
    image: kong:0.14.1
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PG_PORT=5432
      - KONG_PG_DATABASE=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_USER=kong
    command: kong migrations up
    networks:
      - kong-net
    restart: always

  kong:
    image: kong:0.14.1
    depends_on:
      - kong-database
      - kong-migration
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PORT=5432
      - KONG_PG_DATABASE=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_USER=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./logs/kong:/usr/local/kong/logs
    expose:
      - 8000
      - 8001
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 10s
      retries: 10
    networks:
      - kong-net
    restart: always   
      
  kong-dashboard:
    image: pgbi/kong-dashboard
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - kong
    command: start --kong-url http://192.168.1.100:8001
    networks:
      - kong-net
    restart: always 


  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - kong-net
    restart: always

volumes:
  pg-data:
    driver: local
  portainer-data:
    driver: local
          
networks:
  kong-net:

